name: PlivoPythonSDK

on:
  push:
    branches: [ unitTests ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: UnitTests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [2.7, 3.4, 3.5, 3.6, 3.7]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependencies Installation
        run: |
          pip install tox
      - name: Run Tests
        run: |
          tox    
        continue-on-error: true
